const baseUrl = 'www;xyz.com';
const tokenKey = 'token';
const uuidKey = "uuid";
const nameKey = "name";
const usernameKey = "username";
const profileImageKey = "profileImage";
const emailKey = "email";
const phoneNumberKey = "phoneNumber";
const horizontalPadding = 30.0;
const appID = '80403565e67b41cc8902a6c82803026c';
const token =
    '007eJxTYLh4Su71gQlvvlrqSu6fbJa6sfqBObPuXdNbZpcMDO52+vMpMFgYmBgYm5qZppqZJ5kYJidbWBoYJZolWxhZGBgbGJkl/1q7PbkhkJHBVeI0AyMUgvhsDMl5JfnFxQwMAJdAIAg=';
const channel = 'cntoss';
const broadcasterKey = 'isBroadcaster';
const currency = 'Rs';
const userModel = 'Users';
const rawImage = "https://kshamadevigroup.com/public/img/no-product-found.jpg";
