const baseUrl = 'www;xyz.com';
const tokenKey = 'token';
const uuidKey = "uuid";
const nameKey = "name";
const usernameKey = "username";
const profileImageKey = "profileImage";
const emailKey = "email";
const phoneNumberKey = "phoneNumber";
const horizontalPadding = 30.0;
const appID = '7be8c92885c4450fad47f796f95be65d';
const token =
    '007eJxTYKi+qv/+sk255aWzy0wCfusp8P/lN16fXLixcdr0j399Q/YpMJgnpVokWxpZWJgmm5iYGqQlppiYp5lbmqVZmialmpmmSMzbndwQyMiwOfI7AyMUgvicDMUlRamJuZl56QwMAGIjIzQ=';
const channel = 'streaming';
const broadcasterKey = 'isBroadcaster';
const currency = 'Rs';
const userModel = 'Users';
const rawImage = "https://kshamadevigroup.com/public/img/no-product-found.jpg";
