const baseUrl = 'www;xyz.com';
const tokenKey = 'token';
const uuidKey = "uuid";
const nameKey = "name";
const usernameKey = "username";
const profileImageKey = "profileImage";
const emailKey = "email";
const phoneNumberKey = "phoneNumber";
const horizontalPadding = 30.0;
const appID = '80403565e67b41cc8902a6c82803026c';
const token =
    "007eJxTYNCaHlxs6P43QmhP3wbNnF8Z287aXd2WKPJ7XZ0ec5XIQTcFBgsDEwNjUzPTVDPzJBPD5GQLSwOjRLNkCyMLA2MDI7Nkf/W1yQ2BjAzbH65nYmSAQBCfgyGxNLkkMz+vmIEBAHBqH/Y=";
const channel = 'auctions';
const broadcasterKey = 'isBroadcaster';
const currency = 'Rs';
const userModel = 'Users';
const rawImage = "https://kshamadevigroup.com/public/img/no-product-found.jpg";
