name: dependencies
description: A new Flutter package project.
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=2.18.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  agora_rtc_engine: ^6.0.0
  auto_route: ^5.0.4
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  fluttertoast: ^8.1.2
  flutterfire_ui: ^0.4.3+20
  firebase_auth: ^4.2.3
  firebase_database:
  firebase_storage:
  image_picker:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  shared_preferences: ^2.0.15
  google_sign_in: ^5.4.2
  qr_flutter: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
